version: '3.1'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgresuser
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432
