# Generated by Django 4.2.1 on 2023-05-10 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-completed_at", "updated_at", "created_at"]},
        ),
    ]
